### ISSUE TITLE
Too many different articles on packaging

### ISSUE THREAD

**Issue by Mic92** [nix-community/wiki#22]
These articles explain in one way or the other to create nix packages:

- https://nixos.wiki/wiki/Updating_a_package_in_Nixpkgs
- https://nixos.wiki/wiki/Create_and_debug_nix_packages
- https://nixos.wiki/wiki/Generic_Algorithm_on_Doing_Packaging
- https://nixos.wiki/wiki/Modifying_a_Package

**Comment by makefu** [comment]
I'd suggest that we create a top-level directory on packaging software as this is pretty much the main topic where people have questions. This could be used as entry point to all the subsection and quirks of packaging.

there is also:
* https://nixos.wiki/wiki/Packaging_Binaries 
* https://nixos.wiki/wiki/Packaging_Ruby 
* as well as https://nixos.wiki/wiki/Packaging_Software

**Comment by samueldr** [comment]
I concur with @makefu, making a main article about packaging, which will link to more in-depth knowledge. Otherwise the page is too long.

My opinion on that is that longer pages suck, especially when they are written in a way that present many subjects. It makes scrolling through the page harder, but especially, it makes linking hard. Anchors in mediawiki are built upon the text of the title, breaking links when titles are re-worded.

Though, this shouldn't stop any pages being long, as long as it's about one subject.

**Comment by nyarly** [comment]
As I've been learning Nix, this has been a daunting task only because it seems initially so impenetrable. There's *so many* ways to package software in Nix, and from the outset it's hard to approach.

In my experience, the Nixpkgs manual quickstart is actually really good, and a good reference for how to package a piece of software. I seem glimmers of essential advice in the above pages, but my vote would be to fold that advice into the manual and edit the wiki to direct readers there.

**Comment by makefu** [comment]
I suggest we could add a namespace for Packaging software and add an overview article which lists all the different ways and why/when you would need them.

**Comment by samueldr** [comment]
As a technical detail, namespaces (words followed by colon as in  `Workgroup:` and `Help:`) will not show up in the wiki search results by default. This is why for some sections (e.g.: [NixOS_on_ARM](https://nixos.wiki/wiki/NixOS_on_ARM)) I have started to use sub-pages (e.g.: [NixOS_on_ARM/Raspberry_Pi](https://nixos.wiki/wiki/NixOS_on_ARM/Raspberry_Pi)). This way, they are treated exactly like the other pages with regards to indexing and probably some other technical details like categories.

Otherwise, yes, something like `Packaging/*` for the sub-pages, I really like.

**Comment by makefu** [comment]
sounds good to me 👍

**Comment by makefu** [comment]
Closed by adding two new namespaces `Nixpkgs` and `packaging`. The nixpkgs namespace contains articles especially about working with nixpkgs, packaging contains generic information on how to build and package stuff.

* https://nixos.wiki/wiki/Nixpkgs
* https://nixos.wiki/wiki/Packaging
