### ISSUE TITLE
typo in https://nixos.wiki/wiki/K3s

### ISSUE THREAD

**Issue by UriZafrir** [nix-community/wiki#47]
Hi
I found a typo in nixos.wiki/wiki/K3s 
there's an extra p in "tip" (see screenshot below)

I Was trying to find how to issue a pull request but couldn't find the code of the website on this repository..
since this page:
nixos.wiki/wiki/NixOS_Wiki:Contributing
refers to this repository I do wonder where is code of the website..

![image](https://github.com/nix-community/wiki/assets/35652384/4c7e4435-7135-4f8a-b394-b1cf538deff2)

**Comment by makefu** [comment]
Hi! The wiki is maintained by the users, for the users. In order to make the changes, simply create an account at the wiki 
![image](https://github.com/nix-community/wiki/assets/115218/00f96809-50e1-40ad-870d-50a7dbec4b97)
and make the change by clicking edit:
![image](https://github.com/nix-community/wiki/assets/115218/e787fe62-f4c1-49c6-bd67-cba82039142a)

cheers
